<a href="https://colab.research.google.com/github/Koteswararao-1878/23CSBTB27-28/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
arry = np.array([2,8,6,7,3])
print(arry)
print(type(arry))

[2 8 6 7 3]
<class 'numpy.ndarray'>


In [12]:
import numpy as np
arry1 = np.array({'apple','banana','orange'})
print(arry1)
print(type(arry1))

{'banana', 'orange', 'apple'}
<class 'numpy.ndarray'>


In [13]:
import numpy as np
arry = np.array([[2,5],[4,2]])
arry1 = np.array([[2,5,4,2],[4,2,1,0]])
arry2 = np.array([[2,5,4],[4,2,5],[6,7,8]])
print(arry)
print(arry1)
print(arry2)

[[2 5]
 [4 2]]
[[2 5 4 2]
 [4 2 1 0]]
[[2 5 4]
 [4 2 5]
 [6 7 8]]


In [18]:
import numpy as np
arry1 = np.array([1,3,4,5,6])
arry2 = np.array([2,6,3,4,8])
print(arry1)
print(arry2)
print(np.add(arry1,arry2))
print(np.subtract(arry1,arry2))
print(type(arry1))
print(type(arry2))

[1 3 4 5 6]
[2 6 3 4 8]
[ 3  9  7  9 14]
[-1 -3  1  1 -2]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
